name: app_esportes_universitarios_publico
description: "App geral publico de esportes da plataforma Kyarem."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  supabase_flutter: ^2.12.0
  http: ^1.6.0
  flutter_dotenv: ^6.0.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/icon.png

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/.gitkeep
    - assets/images/icon.png
    - assets/images/splash.png
