name: kyarem_eventos
description: "Área administrativa de Campeonatos."
publish_to: 'none'

version: 1.0.0+4 

environment:
  sdk: '>=3.10.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- BANCO DE DADOS ---
  sqflite: ^2.3.0
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0

  # --- COMUNICAÇÃO ---
  supabase_flutter: ^2.12.0
  dio: ^5.4.3

  # --- INTERFACE E UTILITÁRIOS ---
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.2
  shared_preferences: ^2.5.4
  firebase_core: ^4.5.0
  uuid: ^4.5.3
  wakelock_plus: ^1.5.1
  url_launcher: ^6.3.0
  image_picker: ^1.0.7
  flutter_colorpicker: ^1.1.0
  firebase_messaging: ^16.2.0
  flutter_local_notifications: ^21.0.0
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.4.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

# CONFIGURAÇÕES DE FERRAMENTAS (Nível Raiz)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png" 
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/envelope.svg
    - assets/images/key.svg
    - assets/images/meteor.svg
    - assets/images/icon.png 
    - assets/images/splash.png 
    - .env

  fonts:
    - family: Bebas Neue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf